/*
  js/categories.js
  ----------------
  This is the master category bank. Each entry has:
    - text: what the player sees ("A type of fruit")
    - tags: one or more category groups, used for two things:
        1. Building a *balanced* round (e.g. don't get 12 food categories in a row)
        2. Letting the player toggle whole packs on/off in settings

  Why tags instead of just packs? A category can fit into multiple buckets — a
  movie about food belongs to both "entertainment" and "food". Tags are flexible.

  About 250 categories shipped here. Many come from official Scattergories card
  packs (rounds 1–12 across the various editions). Add your own — just push more
  objects into the array. The game will pick them up on next reload.

  We attach the bank to `Game.categories` so other scripts can read it without
  imports / modules.
*/

window.Game = window.Game || {};

/*
  Tag glossary (used by ui.js to show pack toggles, and by game.js to balance
  rounds). Order matters for display.
*/
Game.CATEGORY_TAGS = [
  { id: 'classic',       label: 'Classic',                hint: 'Original Scattergories staples' },
  { id: 'people',        label: 'People',                  hint: 'Names, jobs, famous folks' },
  { id: 'food',          label: 'Food & Drink',            hint: '' },
  { id: 'places',        label: 'Places',                  hint: 'Cities, countries, locations' },
  { id: 'things',        label: 'Objects',                 hint: 'Stuff you can hold' },
  { id: 'nature',        label: 'Nature & Animals',        hint: '' },
  { id: 'entertainment', label: 'Entertainment',           hint: 'Movies, music, games' },
  { id: 'school',        label: 'School & Work',           hint: 'Subjects, jobs, knowledge' },
  { id: 'abstract',      label: 'Abstract',                hint: 'Feelings, reasons, concepts' },
  { id: 'holiday',       label: 'Holidays & Events',       hint: '' },
  { id: 'body',          label: 'Body & Health',           hint: '' },
  { id: 'transport',     label: 'Transportation',          hint: '' },
  { id: 'spicy',         label: 'Spicy / Adult-ish',       hint: 'A little cheeky — couples mode' },
];

/*
  The actual bank. We list each category once. The keep-it-fresh logic in
  game.js avoids reusing recent ones.
*/
Game.CATEGORIES = [
  // --- Classic Scattergories core (people) ---
  { text: "A boy's name",                              tags: ['classic', 'people'] },
  { text: "A girl's name",                              tags: ['classic', 'people'] },
  { text: "A famous athlete",                           tags: ['classic', 'people'] },
  { text: "A famous singer or musician",                tags: ['classic', 'people'] },
  { text: "A famous actor or actress",                  tags: ['classic', 'people'] },
  { text: "A US president",                             tags: ['people'] },
  { text: "A historical figure",                        tags: ['people'] },
  { text: "A cartoon character",                        tags: ['classic', 'people', 'entertainment'] },
  { text: "A superhero",                                tags: ['people', 'entertainment'] },
  { text: "A movie villain",                            tags: ['people', 'entertainment'] },
  { text: "A reality TV personality",                   tags: ['people', 'entertainment'] },
  { text: "A talk show host",                           tags: ['people', 'entertainment'] },
  { text: "A comedian",                                 tags: ['people', 'entertainment'] },
  { text: "A famous chef",                              tags: ['people', 'food'] },
  { text: "A famous author",                            tags: ['people', 'entertainment'] },
  { text: "A scientist or inventor",                    tags: ['people', 'school'] },
  { text: "A profession / occupation",                  tags: ['people', 'school'] },
  { text: "A nickname",                                 tags: ['people'] },
  { text: "A celebrity couple",                         tags: ['people', 'entertainment'] },
  { text: "A name for a pet",                           tags: ['people', 'nature'] },

  // --- Food & Drink ---
  { text: "A fruit",                                    tags: ['classic', 'food'] },
  { text: "A vegetable",                                tags: ['classic', 'food'] },
  { text: "A type of bread",                            tags: ['food'] },
  { text: "A type of cheese",                           tags: ['food'] },
  { text: "A type of pasta or noodle",                  tags: ['food'] },
  { text: "A type of soup",                             tags: ['classic', 'food'] },
  { text: "A pizza topping",                            tags: ['classic', 'food'] },
  { text: "A breakfast food",                           tags: ['food'] },
  { text: "A junk food",                                tags: ['food'] },
  { text: "A dessert",                                  tags: ['food'] },
  { text: "A candy",                                    tags: ['food'] },
  { text: "A cocktail",                                 tags: ['food'] },
  { text: "A non-alcoholic drink",                      tags: ['food'] },
  { text: "A spice or herb",                            tags: ['food'] },
  { text: "An ice cream flavor",                        tags: ['food'] },
  { text: "A type of sandwich",                         tags: ['classic', 'food'] },
  { text: "A type of meat",                             tags: ['food'] },
  { text: "Seafood",                                    tags: ['food'] },
  { text: "A salad ingredient",                         tags: ['classic', 'food'] },
  { text: "Something you grill",                        tags: ['food'] },
  { text: "Something in a refrigerator",                tags: ['classic', 'food', 'things'] },
  { text: "A buffet item",                              tags: ['food'] },
  { text: "A type of cake",                             tags: ['food'] },
  { text: "A type of pie",                              tags: ['food'] },
  { text: "A type of cookie",                           tags: ['food'] },
  { text: "A type of nut",                              tags: ['food'] },
  { text: "A type of bean",                             tags: ['food'] },
  { text: "A condiment",                                tags: ['food'] },
  { text: "A breakfast cereal",                         tags: ['food'] },
  { text: "A Mexican dish",                             tags: ['food'] },
  { text: "An Italian dish",                            tags: ['food'] },
  { text: "A Chinese dish",                             tags: ['food'] },
  { text: "A Thai dish",                                tags: ['food'] },
  { text: "An Indian dish",                             tags: ['food'] },
  { text: "Comfort food",                               tags: ['food'] },
  { text: "A snack food",                               tags: ['food'] },
  { text: "Birthday party food",                        tags: ['food', 'holiday'] },
  { text: "Something you eat with chopsticks",          tags: ['food'] },
  { text: "A coffee drink",                             tags: ['food'] },
  { text: "A pizza chain",                              tags: ['food', 'places'] },
  { text: "A fast food restaurant",                     tags: ['food', 'places'] },
  { text: "A frozen food",                              tags: ['food'] },
  { text: "A finger food",                              tags: ['food'] },
  { text: "Something you eat raw",                      tags: ['food'] },
  { text: "Something you put on toast",                 tags: ['food'] },
  { text: "A leafy green",                              tags: ['food'] },
  { text: "A picnic food",                              tags: ['food'] },

  // --- Places ---
  { text: "A country",                                  tags: ['classic', 'places'] },
  { text: "A city",                                     tags: ['classic', 'places'] },
  { text: "A US state",                                 tags: ['classic', 'places'] },
  { text: "A capital city",                             tags: ['places'] },
  { text: "A continent",                                tags: ['places'] },
  { text: "A body of water",                            tags: ['classic', 'places', 'nature'] },
  { text: "A mountain or volcano",                      tags: ['places', 'nature'] },
  { text: "A national park",                            tags: ['places', 'nature'] },
  { text: "A landmark",                                 tags: ['places'] },
  { text: "A type of store",                            tags: ['places'] },
  { text: "A theme park or attraction",                 tags: ['places'] },
  { text: "An island",                                  tags: ['places', 'nature'] },
  { text: "A vacation destination",                     tags: ['places'] },
  { text: "A place you'd hate to be stuck",             tags: ['places', 'abstract'] },
  { text: "A place to swim",                            tags: ['places'] },
  { text: "A romantic place",                           tags: ['places', 'spicy'] },
  { text: "Something at the beach",                     tags: ['classic', 'things', 'places'] },
  { text: "Something in a kitchen",                     tags: ['classic', 'things', 'places'] },
  { text: "Something in a hospital",                    tags: ['things', 'places'] },
  { text: "Something in a library",                     tags: ['things', 'places'] },
  { text: "Something in a school",                      tags: ['things', 'places'] },
  { text: "Something in a hotel room",                  tags: ['things', 'places'] },
  { text: "Something at the zoo",                       tags: ['things', 'places', 'nature'] },
  { text: "Something at the airport",                   tags: ['things', 'places'] },
  { text: "Something at a gym",                         tags: ['things', 'places'] },
  { text: "Something in a garage",                      tags: ['things', 'places'] },
  { text: "Something at a park",                        tags: ['classic', 'things', 'places'] },
  { text: "Something in your bedroom",                  tags: ['things', 'places'] },
  { text: "Something in a bathroom",                    tags: ['things', 'places'] },
  { text: "Something at a circus",                      tags: ['classic', 'things', 'places'] },
  { text: "Something in a desert",                      tags: ['things', 'places', 'nature'] },
  { text: "Something at a wedding",                     tags: ['things', 'holiday'] },
  { text: "A bar or pub item",                          tags: ['things', 'places'] },
  { text: "Something in your purse / wallet",           tags: ['things', 'places'] },
  { text: "A famous bridge",                            tags: ['places'] },

  // --- Objects / Things ---
  { text: "Something red",                              tags: ['things'] },
  { text: "Something round",                            tags: ['things'] },
  { text: "Something sharp",                            tags: ['things'] },
  { text: "Something sticky",                           tags: ['things'] },
  { text: "Something heavy",                            tags: ['things'] },
  { text: "Something loud",                             tags: ['things'] },
  { text: "Something soft",                             tags: ['things'] },
  { text: "Something that floats",                      tags: ['things'] },
  { text: "Something that flies",                       tags: ['things'] },
  { text: "Something that bounces",                     tags: ['things'] },
  { text: "Something that glows",                       tags: ['things'] },
  { text: "Something that melts",                       tags: ['things'] },
  { text: "Something made of glass",                    tags: ['things'] },
  { text: "Something made of wood",                     tags: ['things'] },
  { text: "Something made of metal",                    tags: ['things'] },
  { text: "Something in a desk",                        tags: ['classic', 'things'] },
  { text: "Something in a toolbox",                     tags: ['things'] },
  { text: "Something in a junk drawer",                 tags: ['things'] },
  { text: "Something in a medicine cabinet",            tags: ['things', 'body'] },
  { text: "Something you wear",                         tags: ['classic', 'things'] },
  { text: "Something you wear on your head",            tags: ['things'] },
  { text: "An item of clothing",                        tags: ['things'] },
  { text: "A type of shoe",                             tags: ['things'] },
  { text: "An accessory",                               tags: ['things'] },
  { text: "A toy",                                      tags: ['things'] },
  { text: "A tool",                                     tags: ['things'] },
  { text: "A kitchen utensil",                          tags: ['things'] },
  { text: "Office supplies",                            tags: ['things', 'school'] },
  { text: "Camping gear",                               tags: ['things'] },
  { text: "Cleaning supplies",                          tags: ['things'] },
  { text: "A musical instrument",                       tags: ['things', 'entertainment'] },
  { text: "A weapon",                                   tags: ['things'] },
  { text: "A piece of furniture",                       tags: ['things'] },
  { text: "An electronic device",                       tags: ['things'] },
  { text: "A type of bag",                              tags: ['things'] },
  { text: "Something with wheels",                      tags: ['things', 'transport'] },
  { text: "Something with strings",                     tags: ['things'] },
  { text: "Something with buttons",                     tags: ['things'] },
  { text: "Something you collect",                      tags: ['things'] },
  { text: "Something fragile",                          tags: ['things'] },
  { text: "Something you'd find on a desert island",    tags: ['things'] },

  // --- Nature & Animals ---
  { text: "An animal",                                  tags: ['classic', 'nature'] },
  { text: "A pet",                                      tags: ['nature'] },
  { text: "A wild animal",                              tags: ['nature'] },
  { text: "A farm animal",                              tags: ['nature'] },
  { text: "An insect or bug",                           tags: ['classic', 'nature'] },
  { text: "A bird",                                     tags: ['classic', 'nature'] },
  { text: "A fish",                                     tags: ['classic', 'nature'] },
  { text: "A reptile",                                  tags: ['nature'] },
  { text: "A dog breed",                                tags: ['nature'] },
  { text: "A flower",                                   tags: ['nature'] },
  { text: "A tree",                                     tags: ['nature'] },
  { text: "A weed or wildflower",                       tags: ['nature'] },
  { text: "A type of weather",                          tags: ['nature'] },
  { text: "A natural disaster",                         tags: ['nature'] },
  { text: "Something you'd see in the sky",             tags: ['nature'] },
  { text: "Something in a forest",                      tags: ['nature'] },
  { text: "Something in the ocean",                     tags: ['nature'] },
  { text: "A constellation",                            tags: ['nature', 'school'] },
  { text: "A rock or mineral",                          tags: ['nature'] },
  { text: "A dinosaur",                                 tags: ['nature'] },
  { text: "A mythical creature",                        tags: ['nature', 'entertainment'] },
  { text: "A planet, moon or star",                     tags: ['nature', 'school'] },
  { text: "A nocturnal animal",                         tags: ['nature'] },
  { text: "An endangered species",                      tags: ['nature'] },

  // --- Entertainment ---
  { text: "A movie title",                              tags: ['classic', 'entertainment'] },
  { text: "A TV show",                                  tags: ['classic', 'entertainment'] },
  { text: "A book title",                               tags: ['entertainment'] },
  { text: "A song title",                               tags: ['entertainment'] },
  { text: "A band or artist",                           tags: ['entertainment'] },
  { text: "An album",                                   tags: ['entertainment'] },
  { text: "A video game",                               tags: ['entertainment'] },
  { text: "A board game",                               tags: ['entertainment'] },
  { text: "A card game",                                tags: ['entertainment'] },
  { text: "A sport",                                    tags: ['entertainment'] },
  { text: "An Olympic sport",                           tags: ['entertainment'] },
  { text: "A type of dance",                            tags: ['entertainment'] },
  { text: "A musical genre",                            tags: ['entertainment'] },
  { text: "A movie genre",                              tags: ['entertainment'] },
  { text: "An animated movie",                          tags: ['entertainment'] },
  { text: "A streaming service or channel",             tags: ['entertainment'] },
  { text: "A magazine",                                 tags: ['entertainment'] },
  { text: "A podcast",                                  tags: ['entertainment'] },
  { text: "A hobby",                                    tags: ['entertainment'] },
  { text: "An indoor activity",                         tags: ['entertainment'] },
  { text: "An outdoor activity",                        tags: ['entertainment'] },
  { text: "A Halloween costume",                        tags: ['entertainment', 'holiday'] },
  { text: "A reality TV show",                          tags: ['entertainment'] },
  { text: "A character from a sitcom",                  tags: ['entertainment', 'people'] },
  { text: "A Disney movie",                             tags: ['entertainment'] },
  { text: "A Pixar movie",                              tags: ['entertainment'] },
  { text: "A '90s sitcom",                              tags: ['entertainment'] },
  { text: "A famous love song",                         tags: ['entertainment', 'spicy'] },
  { text: "A song you'd sing at karaoke",               tags: ['entertainment'] },
  { text: "An app on your phone",                       tags: ['entertainment', 'things'] },
  { text: "A YouTuber or streamer",                     tags: ['entertainment', 'people'] },

  // --- School & Work ---
  { text: "A school subject",                           tags: ['school'] },
  { text: "A college major",                            tags: ['school'] },
  { text: "An office job title",                        tags: ['school'] },
  { text: "A reason to be late",                        tags: ['school', 'abstract'] },
  { text: "An excuse you'd give your boss",             tags: ['school', 'abstract'] },
  { text: "Something a teacher might say",              tags: ['school'] },
  { text: "A type of math",                             tags: ['school'] },
  { text: "A scientific term",                          tags: ['school'] },
  { text: "A famous invention",                         tags: ['school'] },
  { text: "A language",                                 tags: ['school'] },
  { text: "A currency",                                 tags: ['school'] },
  { text: "An award or trophy",                         tags: ['school'] },
  { text: "A type of degree",                           tags: ['school'] },
  { text: "A college team or mascot",                   tags: ['school'] },
  { text: "A famous historical event",                  tags: ['school'] },
  { text: "Something you'd find on a resume",           tags: ['school'] },

  // --- Abstract / Concepts ---
  { text: "An emotion",                                 tags: ['abstract'] },
  { text: "A bad habit",                                tags: ['abstract'] },
  { text: "A good habit",                               tags: ['abstract'] },
  { text: "A pet peeve",                                tags: ['abstract'] },
  { text: "A fear or phobia",                           tags: ['abstract'] },
  { text: "An adjective to describe a person",          tags: ['abstract'] },
  { text: "A verb ending in -ing",                      tags: ['abstract'] },
  { text: "A compliment",                               tags: ['abstract'] },
  { text: "A New Year's resolution",                    tags: ['abstract', 'holiday'] },
  { text: "A wish",                                     tags: ['abstract'] },
  { text: "A regret",                                   tags: ['abstract'] },
  { text: "Something that makes you happy",             tags: ['abstract'] },
  { text: "Something that makes you angry",             tags: ['abstract'] },
  { text: "A reason to call 911",                       tags: ['classic', 'abstract'] },
  { text: "A reason to cry",                            tags: ['abstract'] },
  { text: "A reason to celebrate",                      tags: ['abstract'] },
  { text: "Something you yell",                         tags: ['abstract'] },
  { text: "Something you whisper",                      tags: ['abstract'] },
  { text: "A white lie",                                tags: ['abstract'] },
  { text: "A superpower",                               tags: ['abstract', 'entertainment'] },
  { text: "Something that's overrated",                 tags: ['abstract'] },
  { text: "Something that's underrated",                tags: ['abstract'] },

  // --- Holidays & Events ---
  { text: "A holiday",                                  tags: ['holiday'] },
  { text: "Something at a wedding",                     tags: ['holiday'] },
  { text: "Something at a funeral",                     tags: ['holiday'] },
  { text: "A birthday party item",                      tags: ['holiday'] },
  { text: "A gift you'd give someone",                  tags: ['holiday'] },
  { text: "Something Christmas-related",                tags: ['holiday'] },
  { text: "Something Halloween-related",                tags: ['holiday'] },
  { text: "Something at a baby shower",                 tags: ['holiday'] },
  { text: "A wedding gift",                             tags: ['holiday'] },
  { text: "A Valentine's Day gift",                     tags: ['holiday', 'spicy'] },
  { text: "Something you'd see at a parade",            tags: ['holiday'] },
  { text: "A traditional Thanksgiving dish",            tags: ['holiday', 'food'] },
  { text: "A summer activity",                          tags: ['holiday'] },
  { text: "A winter activity",                          tags: ['holiday'] },

  // --- Body & Health ---
  { text: "A body part",                                tags: ['body'] },
  { text: "A muscle or organ",                          tags: ['body'] },
  { text: "A medical specialty",                        tags: ['body'] },
  { text: "A disease or illness",                       tags: ['body'] },
  { text: "A type of exercise",                         tags: ['body'] },
  { text: "A symptom",                                  tags: ['body'] },
  { text: "A type of medicine",                         tags: ['body'] },
  { text: "A hairstyle",                                tags: ['body'] },
  { text: "Something in a first aid kit",               tags: ['body', 'things'] },
  { text: "A yoga pose or stretch",                     tags: ['body'] },

  // --- Transportation ---
  { text: "A make of car",                              tags: ['transport'] },
  { text: "A model of car",                             tags: ['transport'] },
  { text: "A boat or ship",                             tags: ['transport'] },
  { text: "An aircraft",                                tags: ['transport'] },
  { text: "Public transportation",                      tags: ['transport'] },
  { text: "Something at a gas station",                 tags: ['transport', 'places'] },
  { text: "A reason your car won't start",              tags: ['transport', 'abstract'] },
  { text: "An accessory for a bike",                    tags: ['transport'] },
  { text: "Something on a road trip playlist",          tags: ['transport', 'entertainment'] },

  // --- Spicy / cheeky (couples mode) ---
  // Off by default — toggle in settings if you want the silly ones.
  { text: "Something you'd find under the bed",         tags: ['spicy', 'things'] },
  { text: "A pet name for your partner",                tags: ['spicy', 'people'] },
  { text: "A reason to skip date night",                tags: ['spicy', 'abstract'] },
  { text: "Something you'd never tell your in-laws",    tags: ['spicy', 'abstract'] },
  { text: "A romantic movie",                           tags: ['spicy', 'entertainment'] },
  { text: "A first-date red flag",                      tags: ['spicy', 'abstract'] },
  { text: "Something you'd buy at a honeymoon suite",   tags: ['spicy', 'things'] },
];

/*
  Helper used by game.js to filter the bank by enabled packs.
  An entry is kept if at least one of its tags is in the enabled set.
*/
Game.filterCategoriesByPacks = function (enabledPacks) {
  if (!enabledPacks || enabledPacks.length === 0) return Game.CATEGORIES.slice();
  const set = new Set(enabledPacks);
  return Game.CATEGORIES.filter((c) => c.tags.some((t) => set.has(t)));
};
